# -*- coding: utf-8 -*-
"""kadai_014

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14rx8ztjANKpl_4cxAVTYYk4vvvU4gmsv
"""

def total():
    price1 = 100
    price2 = 200
    return price1 + price2

tax = 1.1

print (total() * tax)