# -*- coding: utf-8 -*-
"""kadai_011

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-3a0IKrOL50p1xQVI3OLISskLUdoSyPu
"""

list = ["水","金","地","火","木","土","天","海","冥"]

for i in list:
  print(i)

i = 1

while i != 9
  print

list = ["水","金","地","火","木","土","天","海","冥"]

index = 0

while index <= 8:
  print(list[index])
  index = index + 1