# -*- coding: utf-8 -*-
"""kadai_005

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19eRg3gqaNABUizjwMb5Fbco__Wt-6Wnm
"""

top = 10
bottom = 20
hight = 5

print(str((top + bottom) * hight / 2) + "cm²")