# -*- coding: utf-8 -*-
"""kadai_013

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SuNY-OLnEz7HFUGweWxwLT0JIpZDWOIw
"""

def calculate_total(price, tax):
  total = price * tax
  print(f"{total}円")

calculate_total(500, 1.1)